[package]
name = "andrea/repo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
fusion = "mattschrubb/fusion@1.2.5"
rblx-nonvoxel-greedy-meshing = "royal0959/rblx-nonvoxel-greedy-meshing@1.0.3"
trove = "cody-nelson/trove@0.0.1"